services:
  spring-app:
    image: dongwook24/spring-cgv:latest
    container_name: spring-app
    ports:
      - "80:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - PAYMENT_STORE_ID=${PAYMENT_STORE_ID}
      - PAYMENT_BASE_URL=${PAYMENT_BASE_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7-alpine
    container_name: spring-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:
