version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  redis-server:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --maxmemory 1gb --maxmemory-policy allkeys-lru --appendonly yes --activedefrag yes
    networks:
      - app-network

  app:
    image: taeik21/cgv-app-new:latest
    container_name: test
    restart: unless-stopped
    volumes:
      - /home/ubuntu/logs:/logs
    ports:
      - "80:8080"
    env_file:
      - .env
    depends_on:
      - redis-server
    networks:
      - app-network

  alloy:
    image: grafana/alloy:v1.8.2
    container_name: alloy
    restart: unless-stopped
    volumes:
      - /home/ubuntu/logs:/logs:ro
      - /var/log:/var/log:ro
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - ./alloy/positions:/var/lib/alloy/data
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
    ports:
      - "12345:12345"
    depends_on:
      - app
    networks:
      - app-network