spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${db_name}?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8
    username: root
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: ${JWT_SECRET_KEY}
  token-validity-in-seconds: ${JWT_VALIDITY}

payment:
  base-url: ${PAYMENT_SERVER} # 결제 서버 주소
  store-id: ${GITHUB_ID}      # 가맹점 식별자
  secret-key: ${PAYMENT_SECRET_KEY}


springdoc:
  swagger-ui:
    path: /swagger-ui.html    # 스웨거 접속 주소
    groups-order: DESC        # 그룹 정렬 순서
    operations-sorter: method # HTTP 메서드순으로 정렬 (GET, POST...)
    display-request-duration: true # 요청 소요 시간 표시
  api-docs:
    path: /api-docs           # OpenAPI 명세서가 JSON으로 나오는 경로
  default-consumes-media-type: application/json
  default-produces-media-type: application/json