spring:
  profiles:
    include: secret

  datasource:
    main:
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        pool-name: MainHikariPool
    lock:
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 5
        pool-name: LockHikariPool

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

payment:
  base-url: 'https://ceos.diggindie.com/'
  store-id: 'Jong0128'

logging:
  level:
    org.hibernate.SQL: debug