spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create #임시
    show-sql: false
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: 6379

jwt:
  secret: ${SECRET_KEY}
  access-token-validity-in-milliseconds: 1800000
  refresh-token-validity-in-milliseconds: 1209600000

management:
  metrics:
    tags:
      env: production

logging:
  level:
    root: INFO
    com.ceos23.spring_boot: DEBUG