spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: Y2Vvcy1qd3Qtc2VjcmV0LWtleS1mb3Itc3ByaW5nLWNndi0yM3JkLWF1dGgtcHJvamVjdC0yMDI2LXNlY3VyZS1rZXktZm9yLWhzNTEy
  access-token-validity-in-seconds: 3600