spring:
  application:
    name: spring-boot

  datasource:
    url: jdbc:mysql://localhost:3306/${database}?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8
    username: root
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug

jwt:
  secret: cGUxq8+7npM2ivr6ge6xjVttZDAod9XD+Qlbyn1jFqUajswLXoFHfbHXdn75FGhPDw1aEAwkwpcfJl8SaFafHA==
  token-validity-in-seconds: 3600
