spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/cgv_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: ${JWT_SECRET}

payment:
  secret-key: ${PAYMENT_SECRET_KEY}
